Support dark mode and dynamic Look and Feel switching
zaproxy/zap-extensions pull request #2554
Opened 2020-09-30 10:36 UTC by psiinon

Depends on https://github.com/zaproxy/zaproxy/pull/6202

Part of https://github.com/zaproxy/zaproxy/issues/5542

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

2020-09-30 11:46 UTC, kingthorin requested changes

2020-09-30 11:46 UTC, kingthorin commented on addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/CommandPanel.java
> +                }
Since this same code appears 3 times with the only difference being the object it's being applied to maybe just extract a method?

2020-09-30 11:46 UTC, kingthorin commented on addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/CommandPanel.java
> +                }
Maybe also extract the xml file path to a constant?

2020-10-07 15:32 UTC, psiinon commented
Updated based on the comments :)

2020-10-07 15:54 UTC, kingthorin approved these changes

2020-10-07 16:10 UTC, thc202 approved these changes

2020-10-07 16:10 UTC, thc202 commented
Thanks! You'll have to push again...

2020-10-07 16:15 UTC, kingthorin approved these changes
Looks good, thanks ⭐

2020-10-07 17:57 UTC, merged