Combined all themes in single template file.
zaproxy/zap-extensions pull request #2961
Opened 2021-06-01 07:14 UTC by Scopestyle

All themes are now combined in a single template "modern".

Kind regards,

Erik

2021-06-01 07:38 UTC, thc202 commented
The commit needs to be signed off: https://github.com/zaproxy/zap-extensions/pull/2961/checks?check_run_id=2716192832

2021-06-01 08:24 UTC, Scopestyle commented
@thc202 Commit is now signed off. 👍

2021-06-01 10:44 UTC, kingthorin commented
Your git config doesn't seem to match your GitHub account info.
wk.local?
https://github.com/zaproxy/zap-extensions/commit/b22cf70a7f6bca2d9a9be821efc5a8afdbf425a6.patch

2021-06-01 11:43 UTC, Scopestyle commented
@kingthorin I'm not an avid GIT user, is this really a problem? What do I have to do to get this merged?

2021-06-01 13:27 UTC, kingthorin commented
No no, if you don't care it doesn't matter.

2021-06-04 16:04 UTC, psiinon requested changes
Just spotted pone string that needs to be internationalized, other than that its looking very good to me :)

2021-06-04 16:04 UTC, psiinon commented on addOns/reports/src/main/zapHomeFiles/reports/modern/report.html
> +				<footer>Report by <a href="https://www.zaproxy.org/" target="_blank">ZAP</a></footer>
This should be i18n'd

2021-06-09 08:07 UTC, psiinon commented
It will require a spotless apply in order to pass the build, eg `./gradlew :addOns:reports:spotlessApply`

2021-06-09 14:42 UTC, psiinon commented
Replaced by #2976

2021-06-09 14:42 UTC, closed without merging

2021-06-17 14:58 UTC, kingthorin commented
@Scopestyle #2976 has been merged now, how would you like to appear in the credits? (Have a look at the current entries and let us know)

https://www.zaproxy.org/docs/desktop/credits/#zap-extended-team

2021-06-17 18:53 UTC, Scopestyle commented
@kingthorin Feel free to add my name and Twitter Handle: Erik de Kuijper ([@edkpr](https://www.twitter.com/edkpr))
Thank you!