fix #6731 - replaced dead CORS misconfiguration reference URL
zaproxy/zap-extensions pull request #3066
Opened 2021-08-10 12:43 UTC by securestep9

Replaced the dead URL in Cross-Domain misconfiguration with correct updated URL:

https://vulncat.fortify.com/en/detail?id=desc.config.dotnet.html5_overly_permissive_cors_policy

2021-08-10 12:51 UTC, ricekot approved these changes

2021-08-10 12:52 UTC, ricekot commented
To address the DCO requirement you'll need to sign-off the commit(s):

https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

2021-08-10 12:56 UTC, kingthorin submitted a review, later dismissed
Thanks @securestep9 , just need you to signoff the commit (you'll need to force push after amending)

2021-08-10 12:58 UTC, kingthorin requested changes
Please also add a fix note tot he [CHANGELOG.md](https://github.com/zaproxy/zap-extensions/blob/main/addOns/pscanrules/CHANGELOG.md) in the unreleased section.

2021-08-17 17:17 UTC, kingthorin reviewed
Looks good to me, just needs the extra changelog entry removed.

2021-08-17 17:17 UTC, kingthorin commented on addOns/pscanrules/CHANGELOG.md
> +
```suggestion
```

I'm guessing that's just a copy/paste error.

2021-08-18 09:22 UTC, thc202 commented on addOns/pscanrules/CHANGELOG.md
> +- Fixed reference URL on CORS micsonfiguration
```suggestion
- Fixed reference URL on CORS misconfiguration.
```

2021-08-18 09:34 UTC, thc202 commented
Addressed the comments.

2021-08-18 09:34 UTC, thc202 approved these changes

2021-08-18 09:34 UTC, thc202 commented
Thank you!

2021-08-18 09:41 UTC, psiinon approved these changes

2021-08-18 10:23 UTC, kingthorin approved these changes
Thank you both

2021-08-18 10:23 UTC, merged