scripts: Persist default keep/replace behaviour
zaproxy/zap-extensions pull request #4946
Opened 2023-09-28 04:53 UTC by ricekot

## Overview
Allow the user to select the default behaviour when a script open in the Script Console changes on disk.

## Related Issues
- Closes zaproxy/zaproxy#5463
- Closes zaproxy/zaproxy#7582

## Checklist
- [x] Update help
- [x] Update changelog
- [x] Run `./gradlew spotlessApply` for code formatting
- [ ] Write tests
- [ ] Check code coverage
- [x] Sign-off commits
- [x] Squash commits
- [x] Use a descriptive title

2023-09-28 13:04 UTC, thc202 commented on addOns/scripts/src/main/javahelp/org/zaproxy/zap/extension/scripts/resources/help/contents/options.html
> +<h2>When The Script in the Console Changes on Disk</h2>
`the`

2023-09-28 13:09 UTC, thc202 commented
It happens that even if you have "Keep Script" you might end up being prompted, when you edit/run the script outside of ZAP. (I'd not have expected that since the user didn't edit the script in ZAP thus not changing it there.)

2023-09-29 10:36 UTC, ricekot commented
Addressed review comments, and replaced the 5-second polling logic with a WatchService as discussed on IRC.

2023-10-02 10:18 UTC, thc202 commented on addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
> +            LOGGER.error(
I'd use `warn`, this would not be a problem/bug in ZAP.

2023-10-02 10:18 UTC, thc202 commented on addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
> +                                if (!changedFileName.equals(script.getName())) {
The file name and script name might not be always the same, would be better to check the `Path`s instead.

2023-10-02 10:18 UTC, thc202 commented on addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
> +                LOGGER.error(
`warn`?

2023-10-02 10:18 UTC, thc202 commented on addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ConsolePanel.java
> +                        "Failed to register watch service for script file: " + script.getFile(), e);
`{}`

2023-10-02 10:18 UTC, thc202 commented on addOns/scripts/src/main/java/org/zaproxy/zap/extension/scripts/ExtensionScriptsUI.java
> +            optionsDialog.addParamPanel(scriptNode, new ScriptConsoleOptionsPanel(), true);
Needs to be removed on `unload`.

2023-10-02 12:02 UTC, thc202 approved these changes

2023-10-02 12:02 UTC, thc202 commented
Thank you!

2023-10-02 13:35 UTC, psiinon requested changes
This works well if the script is selected .. but not if it is not :/

2023-10-02 13:36 UTC, psiinon commented
To reproduce the problem:

- Add a script to ZAP
- Select a different script
- Edit the first script in another app
- Select the script again in ZAP

ZAP doesnt notice the changes.

2023-10-03 09:43 UTC, thc202 approved these changes

2023-10-03 10:27 UTC, kingthorin approved these changes

2023-10-03 10:27 UTC, kingthorin commented
@psiinon do you want to re-test?

2023-10-03 11:06 UTC, psiinon approved these changes

2023-10-03 11:06 UTC, merged