[WIP] ascanrulesAlpha: add rule for MongoDB time tests
zaproxy/zap-extensions pull request #5228
Opened 2024-01-19 14:29 UTC by thc202

Move time based tests to its own rule, ID 90039.

2024-01-19 16:25 UTC, thc202 commented
Ready for review.

2024-01-20 08:37 UTC, kingthorin approved these changes
LGTM

2024-01-22 09:39 UTC, psiinon requested changes
Looks good, just a couple of suggestions..

2024-01-22 09:39 UTC, psiinon commented on addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionTimingScanRule.java
> + * Copyright 2018 The ZAP Development Team
2024?

2024-01-22 09:39 UTC, psiinon commented on addOns/ascanrulesAlpha/src/main/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionTimingScanRule.java
> +                    CommonAlertTag.WSTG_V42_INPV_05_SQLI);
I think a `CommonAlertTag.TEST_TIMING` or similar would be _really_ useful.
Esp if/when (hopefully when) we support tag based policy rules, eg "inc: ["OWASP_2021_*"], exc: ["TEST_TIMING"]` if you see what I mean...

2024-01-22 09:39 UTC, psiinon commented on addOns/ascanrulesAlpha/src/test/java/org/zaproxy/zap/extension/ascanrulesAlpha/MongoDbInjectionTimingScanRuleUnitTest.java
> + * Copyright 2021 The ZAP Development Team
2024

2024-01-22 10:46 UTC, thc202 commented
Comments addressed.

2024-01-22 10:52 UTC, kingthorin approved these changes

2024-01-22 11:27 UTC, psiinon approved these changes

2024-01-22 11:28 UTC, merged